version: "3"

services:
  database:
    image: postgres:14
    ports: [5432:5432]
    environment:
      POSTGRES_DB: meet
      POSTGRES_USER: meet
      POSTGRES_PASSWORD: meet
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /volume/pgdata
    volumes:
      - database:/volume

  redis:
    image: redis:6.2
    ports: [6379:6379]

  api:
    image: node:16
    working_dir: /usr/src/app
    command: yarn dev
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://meet:meet@database:5432/meet?schema=public&connect_timeout=300
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET_KEY: cookies-and-creams
    labels:
      traefik.http.routers.api.rule: PathPrefix(`/api`)
      traefik.http.services.api.loadbalancer.server.port: 3000

    volumes:
      - ./api:/usr/src/app

  web:
    image: node:16
    working_dir: /usr/src/app
    command: yarn dev
    ports: [3010:3010]
    environment:
      HOST: 0.0.0.0
      PORT: 3001
      BACKEND_URL: 'http://backend:3000'
    labels:
      traefik.http.routers.web.rule: PathPrefix(`/`)
      traefik.http.services.web.loadbalancer.server.port: 3001
    volumes:
      - ./web:/usr/src/app

volumes:
  database: {}
